module.exports = {
    testEnvironment: 'node',
    roots: ['<rootDir>/src/__tests__'],
    testMatch: ['**/*.test.ts'],
    moduleFileExtensions: ['ts', 'js', 'json'],
    transform: {
        '^.+\\.ts$': [
            'ts-jest',
            {
                tsconfig: {
                    target: 'ES2022',
                    module: 'commonjs',
                    moduleResolution: 'node',
                    rootDir: '.',
                    baseUrl: './src',
                    paths: {
                        '@/*': ['*'],
                        '@application/*': ['application/*'],
                        '@bootstrap/*': ['bootstrap/*'],
                        '@config/*': ['config/*'],
                        '@domain': ['domain/index.ts'],
                        '@domain/*': ['domain/*'],
                        '@infrastructure/*': ['infrastructure/*'],
                        '@shared/*': ['utils/*'],
                    },
                    outDir: './.ts-jest',
                    esModuleInterop: true,
                    allowSyntheticDefaultImports: true,
                    resolveJsonModule: true,
                    ignoreDeprecations: '6.0',
                    types: ['node', 'jest'],
                },
            },
        ],
    },
    moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
        '^@application/(.*)$': '<rootDir>/src/application/$1',
        '^@bootstrap/(.*)$': '<rootDir>/src/bootstrap/$1',
        '^@config/(.*)$': '<rootDir>/src/config/$1',
        '^@domain$': '<rootDir>/src/domain/index.ts',
        '^@domain/(.*)$': '<rootDir>/src/domain/$1',
        '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
        '^@shared/(.*)$': '<rootDir>/src/utils/$1',
    },
    testPathIgnorePatterns: ['/dist/', '/.ts-jest/'],
};
