import type { AppConfig } from '@config/appConfig';

export const buildTestConfig = (overrides: Partial<AppConfig> = {}): AppConfig => {
    const runMode = overrides.runMode || 'paper';
    const strategyKind = overrides.strategyKind || 'fixed_amount';
    const sourceWallet = overrides.sourceWallet || 'source';
    const targetWallet = overrides.targetWallet || 'target';

    return {
        envFilePath: '.env.test',
        nodeEnv: 'test',
        logLevel: 'silent',
        logFilePath: undefined,
        runMode,
        strategyKind,
        sourceWallet,
        targetWallet,
        mongoUri: 'mongodb://localhost/test',
        scopeKey: `${sourceWallet}:${targetWallet}:${runMode}:${strategyKind}`,
        monitorIntervalMs: 1000,
        monitorInitialLookbackMs: 1000,
        monitorOverlapMs: 1000,
        activitySyncLimit: 100,
        activityAdjacentMergeWindowMs: 1000,
        snapshotStaleAfterMs: 1000,
        retryBackoffMs: 1000,
        maxRetryCount: 3,
        copytradeDispatchConcurrency: 2,
        copytradeProcessingLeaseMs: 300_000,
        settlementIntervalMs: 1000,
        settlementMaxTasksPerRun: 8,
        fixedTradeAmountUsdc: 1,
        proportionalCopyRatio: 1,
        maxOpenPositions: 4,
        maxActiveExposureUsdc: 10,
        maxSignalAgeMs: 15_000,
        marketWhitelist: [],
        minSourceBuyUsdc: 0,
        signalMarketScope: 'all',
        signalWeakThresholdUsdc: 1,
        signalNormalThresholdUsdc: 2,
        signalStrongThresholdUsdc: 3,
        signalWeakTicketUsdc: 1,
        signalNormalTicketUsdc: 2,
        signalStrongTicketUsdc: 3,
        paperInitialBalance: 1000,
        clobHttpUrl: 'https://clob.polymarket.com',
        clobWsUrl: 'wss://ws-subscriptions-clob.polymarket.com/ws/market',
        userWsUrl: 'wss://ws-subscriptions-clob.polymarket.com/ws/user',
        dataApiUrl: 'https://data-api.polymarket.com',
        gammaApiUrl: 'https://gamma-api.polymarket.com',
        rpcUrl: 'https://polygon.drpc.org',
        marketWsReconnectMs: 1000,
        userWsReconnectMs: 1000,
        wsHeartbeatMs: 1000,
        marketBookStaleMs: 2500,
        marketWsBootstrapWaitMs: 750,
        orderConfirmationTimeoutMs: 1000,
        orderConfirmationPollMs: 1000,
        orderConfirmationBlocks: 1,
        liveConfirmTimeoutMs: 1000,
        liveReconcileAfterTimeoutMs: 1000,
        liveOrderMinIntervalMs: 100,
        liveSettlementOnchainRedeemEnabled: true,
        maxSlippageBps: 100,
        maxOrderUsdc: 10,
        buyDustResidualMode: 'trim',
        clobSignatureType: 'SAFE',
        proxyWallet: runMode === 'live' ? '0xproxy' : undefined,
        privateKey: runMode === 'live' ? 'a'.repeat(64) : undefined,
        usdcContractAddress: '0x0000000000000000000000000000000000000001',
        ctfContractAddress: '0x0000000000000000000000000000000000000002',
        autoRedeemEnabled: true,
        autoRedeemMaxConditionsPerRun: 1,
        ...overrides,
    };
};
